### ISSUE TITLE
Inaccurate version bound in rdf-0.1.0.3

### ISSUE THREAD

**Issue by hvr** [TravisWhitaker/rdf#1]
As can be seen on https://matrix.hackage.haskell.org/package/rdf@1556010166 the declared compatibility `base >=4.8 && <5.0` isn't accurate, as there's falsifying reports for `base < 4.11`.

There's no immediate action needed on your part as I've already fixed up the metadata on Hackage (see https://hackage.haskell.org/package/rdf-0.1.0.3/revisions/) for the affected release to prevent cabal from selecting unsound build-plans.

The latest build report can be inspected at https://matrix.hackage.haskell.org/package/rdf

**Comment by TravisWhitaker** [comment]
Ah, thanks for catching this; I forgot to bump the lower bound when I adjusted imports to account for SMP.

**Comment by TravisWhitaker** [comment]
Fixed.
