### ISSUE TITLE
what's the best practice for using more than one baseIRI?

### ISSUE THREAD

**Issue by odanoburu** [TravisWhitaker/rdf#3]
in the RDF I'm trying to generate the subjects and objects of a triple have different baseIRIs from the predicates -- how best to handle this when given the type of `triples :: a -> RDFGen Triples`? the only solution that comes to my mind (besides hardcoding IRIs) is to give a `ToRDF` instance to a `newtype` of
```
(IRI -- baseIRI for predicates
, a) -- my object
```

I'm sorry if this is actually easy to do!

**Comment by TravisWhitaker** [comment]
You can use [local](https://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Trans-Reader.html#v:local) to swap out the base IRI in an RDFGen action. The new IRI can be a function of the base IRI you get from `toTriples`, or not (just use `const`):

```Haskell
subIRI :: IRI -> IRI
subIRI = ...
predIRI :: IRI -> IRI
predIRI = ...
objIRI :: IRI -> IRI
objIRI = ...

genSub :: RDFGen Subject
genSub = ...
genPred :: RDFGen Predicate
genPred = ...
genObj :: RDFGen Object
getObj ...

withVaryingIRIs :: RDFGen Subject -> RDFGen Predicate -> RDFGen Object -> RDFGen Triple
withVaryingIRIs s p o = Triple <$> local subIRI s <*> local predIRI p <*> local objIRI o
```

I've never actually needed this functionality, but I have needed to swap out the IRI for all three components, hence `appBaseIRI`. Maybe `RDFGen` should allow the shared `ReaderT` value to vary for each instance, something like:

```Haskell
type RDFGen iri a = ReaderT iri (State Word64) a

class ToRDF a where
    type IRIProvider a
    triples :: a -> RDFGen (IRIProvider a) Triples
```

Admittedly, the way `Data.RDF.ToRDF` works was somewhat specific to the sorts of marshaling I was doing when I wrote this library, so there's definitely room for improvement. I'd be happy to generalize this interface if you've got ideas!

**Comment by odanoburu** [comment]
I guess my biggest hurdle was how not to hardcode IRIs and not anything in the library per se -- I went with putting the proper values in a configuration file and not using the `ToRDF` instance for more flexibility in generating the triples (or I'd have to do the `newtype` trick I mentioned)

>  I'd be happy to generalize this interface if you've got ideas!

I'll post here in case I think of something! I'll close this for now. thanks for the help @TravisWhitaker !
